=== LindirQuenya/locationapp-server/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Config",
  "type": "object",
  "required": [
    "db_path",
    "domain_name",
    "listen",
    "oauth_provider",
    "redirect_after_auth",
    "userinfo_endpoint"
  ],
  "properties": {
    "db_path": {
      "type": "string"
    },
    "domain_name": {
      "type": "string"
    },
    "listen": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ListenSpec"
      }
    },
    "oauth_provider": {
      "$ref": "#/definitions/OauthConfig"
    },
    "redirect_after_auth": {
      "type": "string"
    },
    "userinfo_endpoint": {
      "type": "string"
    }
  },
  "definitions": {
    "ListenSpec": {
      "type": "object",
      "required": [
        "addr",
        "port"
      ],
      "properties": {
        "addr": {
          "type": "string"
        },
        "port": {
          "type": "integer",
          "format": "uint16",
          "minimum": 0.0
        }
      }
    },
    "OauthConfig": {
      "type": "object",
      "required": [
        "auth_url",
        "client_id",
        "client_secret",
        "scopes",
        "token_url"
      ],
      "properties": {
        "auth_url": {
          "type": "string"
        },
        "client_id": {
          "type": "string"
        },
        "client_secret": {
          "type": "string"
        },
        "scopes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "token_url": {
          "type": "string"
        }
      }
    }
  }
}

=== LindirQuenya/locationapp-server/config.example.json
{
	"oauth_provider": {
		"client_id": "OAuth client id here",
		"client_secret": "OAuth client secret here",
		"auth_url": "https://accounts.google.com/o/oauth2/auth",
		"token_url": "https://oauth2.googleapis.com/token",
		"scopes": [
			"https://www.googleapis.com/auth/userinfo.email"
		]
	},
	"domain_name": "sub.my-domain.com",
	"userinfo_endpoint": "https://www.googleapis.com/oauth2/v2/userinfo",
	"redirect_after_auth": "https://sub.my-domain.com/",
	"listen": [
		{
			"addr": "127.0.0.1",
			"port": 8080
		}
	],
	"db_path": "/path/to/location-app.sqlite3"
}
